import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  bookSidebar: [
    {
      type: 'category',
      label: 'Chapter 1: Introduction to Physical AI',
      items: [{type: 'autogenerated', dirName: 'chapter-01-introduction'}],
    },
    {
      type: 'category',
      label: 'Chapter 2: Foundations of Physical AI',
      items: [{type: 'autogenerated', dirName: 'chapter-02-foundations'}],
    },
    {
      type: 'category',
      label: 'Chapter 3: Machine Learning for Physical Systems',
      items: [{type: 'autogenerated', dirName: 'chapter-03-machine-learning'}],
    },
    {
      type: 'category',
      label: 'Chapter 4: Computer Vision in Physical AI',
      items: [{type: 'autogenerated', dirName: 'chapter-04-computer-vision'}],
    },
    {
      type: 'category',
      label: 'Chapter 5: NLP and Robotics',
      items: [{type: 'autogenerated', dirName: 'chapter-05-nlp-robotics'}],
    },
    {
      type: 'category',
      label: 'Chapter 6: Sim-to-Real Transfer',
      items: [{type: 'autogenerated', dirName: 'chapter-06-sim-to-real'}],
    },
    {
      type: 'category',
      label: 'Chapter 7: Embodied AI',
      items: [{type: 'autogenerated', dirName: 'chapter-07-embodied-ai'}],
    },
    {
      type: 'category',
      label: 'Chapter 8: Humanoid Robots',
      items: [{type: 'autogenerated', dirName: 'chapter-08-humanoid-robots'}],
    },
    {
      type: 'category',
      label: 'Chapter 9: Safety and Ethics',
      items: [{type: 'autogenerated', dirName: 'chapter-09-safety-ethics'}],
    },
    {
      type: 'category',
      label: 'Chapter 10: The Future of Physical AI',
      items: [{type: 'autogenerated', dirName: 'chapter-10-future'}],
    },
  ],
};

export default sidebars;
